#!/bin/bash
# ===========================================================================
# Build LAMMPS (stable branch == 22Jul2025 + latest update) on VIPER-GPU.
# Hardware: AMD Instinct MI300A APU  ->  KOKKOS + HIP, arch gfx942 (APU variant).
#
# RUN THIS ON A VIPER LOGIN NODE (viper11i/12i/13i): the package downloads and
# git clone need internet, which only the login nodes have.
#
#   ./build-lammps-viper.sh
#
# Override locations with env vars, e.g.  SRC=/ptmp/$USER/lammps ./build-lammps-viper.sh
# ===========================================================================
# Make the 'module' function available without a LOGIN shell. (We deliberately
# do NOT use '#!/bin/bash -l': on this account the login startup files exit for
# non-interactive shells, so '-l' made the script terminate with no output.)
if ! command -v module >/dev/null 2>&1; then
    for _f in /etc/profile.d/modules.sh \
              "${MODULESHOME:+$MODULESHOME/init/bash}" \
              /mpcdf/soft/SLE_15/packages/x86_64/Modules/5.4.0/init/bash; do
        [ -n "${_f:-}" ] && [ -r "$_f" ] && . "$_f" && break
    done
fi

# --- Module setup FIRST, before `set -euo pipefail`: the Lmod `module` function
#     can return non-zero / reference unset vars and would abort the script
#     silently under strict mode. ---
module purge
module load gcc/14 rocm/6.3 openmpi_gpu/5.0 cmake
# (Alternatively the newer stack: module load gcc/16 rocm/7.2 openmpi_gpu/5.0 cmake)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Build (and git-clone) in the directory you launch this script from, not $HOME.
RUN_DIR="$(pwd)"

# --- Capture EVERYTHING (stdout + stderr) to a timestamped log file while still
#     echoing to the screen. Every warning/error from the module loads, voro++,
#     the cmake configure and the build itself lands in $LOG.
#     Override the path with:  LOG=/ptmp/$USER/viper.log ./build-lammps-viper.sh
LOG="${LOG:-$RUN_DIR/build-viper-$(date +%Y%m%d-%H%M%S).log}"
exec > >(tee -a "$LOG") 2>&1
echo ">> logging this run to: $LOG"

SRC="${SRC:-$RUN_DIR/lammps}"
BUILD="${BUILD:-$SRC/build-viper}"
JOBS="${JOBS:-8}"                 # nvcc/hipcc are memory-hungry; don't overdo -j

# --- source: 'stable' tracks the newest stable release incl. its updates -----
if [ ! -d "$SRC/.git" ]; then
    git clone -b stable https://github.com/lammps/lammps.git "$SRC"
fi
cd "$SRC"

ROCM="${ROCM_PATH:-${ROCM_HOME:-/opt/rocm}}"

# --- pre-build voro++ with the host g++ (VORONOI) --------------------------
# hipcc cannot compile voro++, and LAMMPS would build it with CMAKE_CXX_COMPILER
# (=hipcc). So build voro++ with plain g++ and hand LAMMPS the prebuilt lib.
VORO_VER="${VORO_VER:-0.4.6}"
VORO_DIR="$RUN_DIR/voro++-$VORO_VER"
VORO_LIB="$VORO_DIR/src/libvoro++.a"
VORO_INC="$VORO_DIR/src"
if [ ! -f "$VORO_LIB" ]; then
    echo ">> building voro++ $VORO_VER with g++ (host compiler, not hipcc)"
    ( cd "$RUN_DIR"
      if [ ! -d "$VORO_DIR" ]; then
          curl -fL -o "voro++-$VORO_VER.tar.gz" \
               "https://download.lammps.org/thirdparty/voro++-$VORO_VER.tar.gz"
          tar xzf "voro++-$VORO_VER.tar.gz"
          ( cd "$VORO_DIR" && patch -b -p0 < "$SRC/lib/voronoi/voro-make.patch" )
      fi
      make -C "$VORO_DIR" CXX=g++ CFLAGS="-O3 -fPIC" )
fi
[ -f "$VORO_LIB" ] || { echo "ERROR: voro++ build failed; $VORO_LIB missing" >&2; exit 1; }
echo ">> voro++ lib: $VORO_LIB"

# --- hipcc wrapper: force C++17 + gfx942 on EVERY hipcc invocation -------------
# The real blocker: at project() CMake compiles a throwaway test program with
# hipcc and injects -std=c++98. Under C++98, ROCm 6.3's HIP headers
# (__clang_hip_math.h pulling in libstdc++ <type_traits>) don't compile, so the
# probe reports "compiler is broken". This probe runs not just for LAMMPS but
# for every nested ExternalProject (KIM-API, PACE, ...), each in its own fresh
# cmake — so skipping it at the top level (COMPILER_WORKS) does NOT help the
# sub-projects. And HIPCC_COMPILE_FLAGS_APPEND can't win because hipcc inserts
# it BEFORE CMake's flags and clang honours the LAST -std (the c++98).
#
# Fix: replace the compiler with a wrapper that (a) drops any c++98/03 -std that
# CMake injects and (b) appends -std=c++17 LAST so it always wins, plus pins
# --offload-arch=gfx942 (login nodes have no GPU, so hipcc would default to
# gfx906). Every sub-project inherits this wrapper via CMAKE_CXX_COMPILER, so
# all their probes pass too.
REAL_HIPCC="$(command -v hipcc)"
HIPCC_WRAP="$RUN_DIR/hipcc-cxx17"
cat > "$HIPCC_WRAP" <<EOF
#!/bin/bash
# Auto-generated by build-lammps-viper.sh — forces C++17 + gfx942 for ROCm 6.3.
args=()
for a in "\$@"; do
  case "\$a" in
    -std=c++98|-std=gnu++98|-std=c++03|-std=gnu++03) ;;   # drop CMake's probe std
    *) args+=("\$a") ;;
  esac
done
exec "$REAL_HIPCC" --offload-arch=gfx942 "\${args[@]}" -std=c++17
EOF
chmod +x "$HIPCC_WRAP"
echo ">> hipcc wrapper: $HIPCC_WRAP  (real hipcc: $REAL_HIPCC)"

# Changing the compiler is incompatible with an existing cache: wipe the build
# dir unless it was already configured with this exact wrapper.
if [ -f "$BUILD/CMakeCache.txt" ] && \
   ! grep -q "CMAKE_CXX_COMPILER:.*=${HIPCC_WRAP}\$" "$BUILD/CMakeCache.txt"; then
    echo ">> compiler changed / stale cache — removing $BUILD for a clean configure"
    rm -rf "$BUILD"
fi

cmake -S "$SRC/cmake" -B "$BUILD" \
    -C "$SCRIPT_DIR/cmake/lammps-packages-mpcdf.cmake" \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_STANDARD=17 \
    -D CMAKE_CXX_STANDARD_REQUIRED=ON \
    -D BUILD_MPI=on -D BUILD_OMP=on \
    -D LAMMPS_MACHINE=viper \
    -D MPI_CXX_SKIP_MPICXX=on \
    -D MPI_CXX_COMPILER=mpic++ \
    -D CMAKE_CXX_COMPILER="$HIPCC_WRAP" \
    -D CMAKE_CXX_FLAGS="-munsafe-fp-atomics" \
    -D PKG_PLUMED=off \
    `# ML-UF3 off: pair_uf3_kokkos.cpp builds a HostSpace ScatterView from a` \
    `# HIPSpace view (illegal cross-space copy) -> won't compile on HIP. Not` \
    `# needed for the PACE benchmark. (-D after -C overrides the shared preset.)` \
    -D PKG_ML-UF3=off \
    -D PKG_VORONOI=on -D DOWNLOAD_VORO=off \
    -D VORO_LIBRARY="$VORO_LIB" -D VORO_INCLUDE_DIR="$VORO_INC" \
    -D PKG_KOKKOS=on \
    -D Kokkos_ENABLE_SERIAL=on \
    -D Kokkos_ENABLE_OPENMP=off \
    -D Kokkos_ENABLE_HIP=on \
    -D Kokkos_ARCH_AMD_GFX942_APU=on \
    -D Kokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=on \
    -D FFT=KISS -D FFT_KOKKOS=HIPFFT \
    -D CMAKE_EXE_LINKER_FLAGS="-Wl,-rpath=\$ORIGIN/../lib64 -Wl,-rpath=$ROCM/lib/llvm/lib"

cmake --build "$BUILD" -j "$JOBS"
echo
echo "DONE: $BUILD/lmp_viper"
# Optional smoke test; never abort the (successful) build if the binary can't
# run on the login node.
echo ">> installed packages:"
( "$BUILD/lmp_viper" -h 2>/dev/null | sed -n '/Installed packages/,/^$/p' | head -20 ) \
  || echo "   (could not run lmp_viper on the login node — verify in a job: srun ... $BUILD/lmp_viper -h)"
